server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: poetry-over-tea
  profiles:
    active: local
  # 解决knife4j接口文档异常：Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: ${poetry-over-tea.datasource.driver-class-name}
    url: ${poetry-over-tea.datasource.url}
    username: ${poetry-over-tea.datasource.username}
    password: ${poetry-over-tea.datasource.password}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mahua:
  alioss:
    endpoint: ${my.alioss.endpoint}
    buck-net-name: ${my.alioss.bucketName}
    access-key-id: ${my.alioss.accessKeyId}
    access-key-secret: ${my.alioss.accessKeySecret}
